//! Golden check: the README's sample sessions, `docs/samples/*.txt` and the hero
//! screenshot must match what the binary prints now. Regenerate with
//! `scripts/readme-samples.sh` (`just readme`).

use std::path::Path;
use std::process::Command;

#[test]
fn readme_samples_match_binary_output() {
    if cfg!(windows) {
        // Transcripts are generated by a bash script with Unix paths.
        eprintln!("SKIPPED README sample check: generated and checked on Unix only");
        return;
    }
    let missing: Vec<&str> = ["bash", "python3"].into_iter().filter(|t| !on_path(t)).collect();
    if !missing.is_empty() {
        eprintln!("SKIPPED README sample check: {} not on PATH", missing.join(", "));
        return;
    }
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let out = Command::new("bash")
        .arg(root.join("scripts/readme-samples.sh"))
        .arg("--check")
        .env("GENOME_BIN", env!("CARGO_BIN_EXE_genome"))
        .current_dir(root)
        .output()
        .expect("run scripts/readme-samples.sh (needs bash and python3)");
    assert!(
        out.status.success(),
        "README samples drifted from the binary's output; run `just readme` and commit.\n{}\n{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
}

fn on_path(tool: &str) -> bool {
    std::env::var_os("PATH").is_some_and(|p| std::env::split_paths(&p).any(|d| d.join(tool).is_file()))
}
