//! Consumer genotyping-array exports: 23andMe, AncestryDNA, MyHeritage, FTDNA.
//!
//! All four list pre-chosen SNPs keyed by rsid with GRCh37 positions and
//! genotype letters on the + strand. They carry no reference allele.

use std::io::BufRead;

use super::{InputFormat, SourceInfo};
use crate::error::{AppError, Result};
use crate::model::{array_zygosity, normalize_chrom, Build, Call};

/// Build stated in the comment header, if any.
fn header_build(comments: &str) -> Option<Build> {
    let l = comments.to_ascii_lowercase();
    if l.contains("build 38") || l.contains("grch38") || l.contains("hg38") {
        Some(Build::GRCh38)
    } else if l.contains("build 37") || l.contains("grch37") || l.contains("hg19") {
        Some(Build::GRCh37)
    } else if l.contains("build 36") {
        Some(Build::Unknown)
    } else {
        None
    }
}

fn split_fields(line: &str, format: InputFormat) -> Vec<String> {
    let sep = if line.contains('\t') { '\t' } else { ',' };
    let fields = line.split(sep).map(|f| f.trim().trim_matches('"').to_string());
    match format {
        InputFormat::Myheritage | InputFormat::Ftdna if sep == ',' => fields.collect(),
        _ => fields.collect(),
    }
}

pub fn parse(
    reader: Box<dyn BufRead>,
    format: InputFormat,
    sink: &mut dyn FnMut(Call) -> Result<()>,
) -> Result<SourceInfo> {
    let mut comments = String::new();
    let mut header_seen = false;
    let mut n = 0u64;
    let mut bad = 0u64;
    for (lineno, line) in reader.lines().enumerate() {
        let line = line?;
        let t = line.trim_end_matches(['\r', '\n']);
        if t.trim().is_empty() {
            continue;
        }
        if t.starts_with('#') {
            comments.push_str(t);
            comments.push('\n');
            continue;
        }
        let f = split_fields(t, format);
        if !header_seen && f.first().is_some_and(|h| h.eq_ignore_ascii_case("rsid")) {
            header_seen = true;
            continue;
        }
        let genotype = match (format, f.len()) {
            (InputFormat::Ancestry, 5..) => {
                let (a, b) = (f[3].as_str(), f[4].as_str());
                if a == "0" || b == "0" {
                    "--".to_string()
                } else {
                    format!("{a}{b}")
                }
            }
            (_, 4..) => f[3].replace(' ', ""),
            _ => {
                bad += 1;
                if bad > 1000 && n == 0 {
                    return Err(AppError::invalid(format!(
                        "line {}: not a {} genotype row: {t}",
                        lineno + 1,
                        format.as_str()
                    )));
                }
                continue;
            }
        };
        let Ok(pos) = f[2].parse::<u32>() else {
            bad += 1;
            continue;
        };
        let genotype = if genotype.is_empty() { "--".to_string() } else { genotype.to_ascii_uppercase() };
        let chrom = normalize_chrom(&f[1]);
        let zygosity = Some(array_zygosity(&genotype, None));
        let rsid = Some(f[0].clone()).filter(|s| !s.is_empty() && s != ".");
        sink(Call { chrom, pos, end: pos, rsid, genotype, zygosity, ..Call::default() })?;
        n += 1;
    }
    if n == 0 {
        return Err(AppError::invalid(format!("no genotype rows found ({} format)", format.as_str())));
    }
    let mut warnings = Vec::new();
    if bad > 0 {
        warnings.push(format!("skipped {bad} malformed rows"));
    }
    let (build, evidence) = match header_build(&comments) {
        Some(Build::Unknown) => {
            warnings.push("header states NCBI build 36; positions are not GRCh37/GRCh38".into());
            (Build::Unknown, "header")
        }
        Some(b) => (b, "header"),
        None => {
            warnings.push(format!("{} export has no build header; assuming GRCh37", format.as_str()));
            (Build::GRCh37, "assumed")
        }
    };
    Ok(SourceInfo {
        source_format: format.as_str().to_string(),
        assay: "array",
        build,
        build_evidence: evidence,
        sample: None,
        chip: Some("unknown".into()),
        warnings,
        contigs: Vec::new(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn run(text: &str, format: InputFormat) -> (SourceInfo, Vec<Call>) {
        let mut calls = Vec::new();
        let info = parse(Box::new(std::io::Cursor::new(text.to_string())), format, &mut |c| {
            calls.push(c);
            Ok(())
        })
        .unwrap();
        (info, calls)
    }

    #[test]
    fn twentythree() {
        let (info, calls) = run(
            "# This data file generated by 23andMe\n# More information on reference human assembly build 37 (a.k.a. Annotation Release 104):\n# rsid\tchromosome\tposition\tgenotype\nrs1\t1\t100\tAG\nrs2\tX\t5000000\tA\ni3\tMT\t10\t--\n",
            InputFormat::TwentyThreeAndMe,
        );
        assert_eq!((info.build, info.build_evidence), (Build::GRCh37, "header"));
        assert_eq!(calls.len(), 3);
        assert_eq!(calls[1].zyg(), crate::model::Zygosity::Hemi);
        assert!(!calls[2].is_called());
    }

    #[test]
    fn ancestry_and_ftdna() {
        let (_, calls) = run(
            "#AncestryDNA raw data download\n#human reference build 37.1\nrsid\tchromosome\tposition\tallele1\tallele2\nrs1\t23\t100\tA\tG\nrs2\t25\t200\t0\t0\nrs3\t26\t5\tT\tT\n",
            InputFormat::Ancestry,
        );
        assert_eq!(calls[0].chrom, "X");
        assert_eq!(calls[0].genotype, "AG");
        assert_eq!(calls[1].genotype, "--");
        assert_eq!(calls[2].chrom, "MT");
        let (info, calls) = run("RSID,CHROMOSOME,POSITION,RESULT\n\"rs1\",\"1\",\"100\",\"CT\"\n", InputFormat::Ftdna);
        assert_eq!(info.build_evidence, "assumed");
        assert_eq!(calls[0].genotype, "CT");
    }
}
