#!/usr/bin/env python3
"""Regenerates the synthetic fixtures in this directory. All genotypes are
invented; positions of the curated SNPs are real coordinates, nothing else is
from any real person."""
import random

random.seed(25)
B = "ACGT"


def het(rng):
    a, b = rng.sample(B, 2)
    return a + b


# ---------------------------------------------------------------- arrays (GRCh37)
def array_rows(sex, rng):
    rows = [
        ("rs429358", "19", 45411941, "TC"),   # APOE e4 carrier (het)
        ("rs7412", "19", 45412079, "CC"),     # hom ref
        ("rs1801133", "1", 11856378, "AG"),   # MTHFR C677T het
        ("rs1801131", "1", 11854476, "TT"),
        ("rs6025", "1", 169519049, "CC"),
        ("rs1800562", "6", 26093141, "GG"),
        ("rs4988235", "2", 136608646, "AG"),
        ("rs4244285", "10", 96541616, "GG"),
        ("i3000001", "1", 900000, "II"),
    ]
    for i in range(30):
        g = het(rng) if i % 3 == 0 else rng.choice(B) * 2
        rows.append((f"rs{1000+i}", str(1 + i % 22), 1_000_000 + i * 1000, g))
    rows.append(("rs2000", "1", 2_000_000, "--"))
    # X: 2 PAR1 sites (het in both sexes), 40 non-PAR sites
    rows.append(("rs3000", "X", 100_000, het(rng)))
    rows.append(("rs3001", "X", 2_000_000, het(rng)))
    for i in range(40):
        pos = 10_000_000 + i * 50_000
        if sex == "male":
            g = rng.choice(B) if i % 2 else rng.choice(B) * 2
            if i == 7:
                g = het(rng)  # one noisy het call
        else:
            g = het(rng) if i % 3 == 0 else rng.choice(B) * 2
        rows.append((f"rs{4000+i}", "X", pos, g))
    # Y: 30 sites; male: 26 called, female: none called
    for i in range(30):
        g = (rng.choice(B) if (sex == "male" and i % 8 != 3) else "--")
        rows.append((f"rs{5000+i}", "Y", 3_000_000 + i * 10_000, g))
    rows.append(("rs6000", "MT", 73, "G"))
    return rows


def write_23andme(path, sex, seed):
    rng = random.Random(seed)
    with open(path, "w") as f:
        f.write("# This data file generated by 23andMe at: Mon Jan 01 00:00:00 2024\n")
        f.write("# SYNTHETIC TEST DATA - not a real person.\n")
        f.write("# More information on reference human assembly build 37 (a.k.a. Annotation Release 104):\n")
        f.write("# rsid\tchromosome\tposition\tgenotype\n")
        for r, c, p, g in array_rows(sex, rng):
            f.write(f"{r}\t{c}\t{p}\t{g}\n")


write_23andme("23andme_male.txt", "male", 1)
write_23andme("23andme_female.txt", "female", 2)

rng = random.Random(3)
with open("ancestry.txt", "w") as f:
    f.write("#AncestryDNA raw data download\n#SYNTHETIC TEST DATA\n")
    f.write("#Genotypes were called relative to the + strand of human reference build 37.1\n")
    f.write("rsid\tchromosome\tposition\tallele1\tallele2\n")
    for r, c, p, g in array_rows("female", rng):
        code = {"X": "23", "Y": "24", "MT": "26"}.get(c, c)
        if c == "X" and p < 2_699_520:
            code = "25"
        g2 = (g * 2)[:2] if len(g) == 1 else g
        if g2 == "--":
            a1 = a2 = "0"
        elif g2 in ("II", "DD"):
            continue
        else:
            a1, a2 = g2[0], g2[1]
        f.write(f"{r}\t{code}\t{p}\t{a1}\t{a2}\n")

for name, header in [("myheritage.csv", "# MyHeritage DNA raw data.\n# SYNTHETIC TEST DATA\n# This file was generated relative to the human reference build 37.\n"),
                     ("ftdna.csv", "")]:
    rng = random.Random(4)
    with open(name, "w") as f:
        f.write(header)
        f.write("RSID,CHROMOSOME,POSITION,RESULT\n")
        for r, c, p, g in array_rows("male", rng)[:45]:
            f.write(f'"{r}","{c}","{p}","{g}"\n')

# ---------------------------------------------------------------- VCFs
CONTIGS38 = [("chr1", 248956422), ("chr2", 242193529), ("chr19", 58617616), ("chrX", 156040895), ("chrY", 57227415),
             ("chrM", 16569), ("chr1_KI270706v1_random", 175055), ("chrUn_KI270302v1", 2274),
             ("chr19_KI270938v1_alt", 1066800), ("HLA-A*01:01:01:01", 3503), ("chrEBV", 171823)]
CONTIGS37 = [("1", 249250621), ("2", 243199373), ("19", 59128983), ("X", 155270560), ("Y", 59373566),
             ("MT", 16569), ("GL000192.1", 547496), ("hs37d5", 35477943), ("NC_007605", 171823)]


def vcf_header(f, contigs, sample, ref):
    f.write("##fileformat=VCFv4.2\n")
    f.write("##source=synthetic-test-fixture\n")
    f.write(f"##reference={ref}\n")
    for c, l in contigs:
        f.write(f"##contig=<ID={c},length={l}>\n")
    f.write('##INFO=<ID=DP,Number=1,Type=Integer,Description="Depth">\n')
    f.write('##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">\n')
    f.write('##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Depth">\n')
    f.write('##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="GQ">\n')
    f.write(f"#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\t{sample}\n")


def rec(f, c, p, i, r, a, gt, q=50, flt="PASS", dp=30):
    f.write(f"{c}\t{p}\t{i}\t{r}\t{a}\t{q}\t{flt}\tDP={dp}\tGT:DP:GQ\t{gt}:{dp}:99\n")


# WGS, GRCh38, variant-only, no rsids, male, with alt/decoy/HLA/EBV contigs
rng = random.Random(5)
with open("wgs_grch38.vcf", "w") as f:
    vcf_header(f, CONTIGS38, "SYNTH38", "file:///ref/GRCh38_full_analysis_set_plus_decoy_hla.fa")
    rec(f, "chr1", 11794419, ".", "T", "G", "0/1")         # rs1801131 het
    for i in range(20):
        r, a = rng.sample(B, 2)
        rec(f, "chr1", 20_000_000 + i * 1000, ".", r, a, "0/1" if i % 2 else "1/1")
    rec(f, "chr1", 30_000_000, ".", "AT", "A", "0/1")      # deletion
    rec(f, "chr2", 135851076, ".", "G", "A", "0/1")         # rs4988235 het
    rec(f, "chr19", 44908684, ".", "T", "C", "0/1")         # rs429358 het (APOE e4)
    rec(f, "chr19", 45000000, ".", "G", "A,T", "1/2")
    # X: 30 non-PAR hom-alt (male), 2 PAR het, Y variants
    rec(f, "chrX", 100_000, ".", "A", "G", "0/1")
    rec(f, "chrX", 1_000_000, ".", "C", "T", "0/1")
    for i in range(30):
        r, a = rng.sample(B, 2)
        rec(f, "chrX", 10_000_000 + i * 100_000, ".", r, a, "1/1" if i != 4 else "0/1")
    for i in range(6):
        r, a = rng.sample(B, 2)
        rec(f, "chrY", 3_000_000 + i * 100_000, ".", r, a, "1")
    rec(f, "chrM", 73, ".", "A", "G", "1/1")
    rec(f, "chr1_KI270706v1_random", 1000, ".", "A", "C", "0/1")
    rec(f, "chrUn_KI270302v1", 100, ".", "C", "T", "1/1")
    rec(f, "chr19_KI270938v1_alt", 5000, ".", "G", "A", "0/1")
    rec(f, "HLA-A*01:01:01:01", 200, ".", "T", "C", "0/1")
    rec(f, "chrEBV", 300, ".", "A", "T", "1/1")
    rec(f, "chr1", 40_000_000, ".", "C", "G", "./.", q=".", flt="LowQual", dp=2)

# GRCh37 VCF with rsids, b37 contig naming, decoy contigs
rng = random.Random(6)
with open("wgs_grch37_rsids.vcf", "w") as f:
    vcf_header(f, CONTIGS37, "SYNTH37", "file:///ref/hs37d5.fa")
    rec(f, "1", 11854476, "rs1801131", "T", "G", "0/1")
    rec(f, "1", 11856378, "rs1801133", "G", "A", "1/1")
    for i in range(12):
        r, a = rng.sample(B, 2)
        rec(f, "2", 5_000_000 + i * 1000, f"rs{7000+i}", r, a, "0/1" if i % 2 else "1/1")
    rec(f, "19", 45411941, "rs429358", "T", "C", "0/1")
    for i in range(30):
        r, a = rng.sample(B, 2)
        rec(f, "X", 20_000_000 + i * 100_000, f"rs{8000+i}", r, a, "0/1" if i % 2 else "1/1")  # female-like
    rec(f, "GL000192.1", 100, ".", "A", "G", "0/1")
    rec(f, "hs37d5", 100, ".", "A", "G", "1/1")
    rec(f, "NC_007605", 100, ".", "A", "G", "1/1")

# gVCF GRCh38 with reference blocks
with open("sample.g.vcf", "w") as f:
    f.write("##fileformat=VCFv4.2\n##GVCFBlock0-1=minGQ=0(inclusive),maxGQ=1(exclusive)\n")
    f.write('##ALT=<ID=NON_REF,Description="Any non-reference allele">\n')
    f.write('##INFO=<ID=END,Number=1,Type=Integer,Description="End">\n')
    for c, l in CONTIGS38[:6]:
        f.write(f"##contig=<ID={c},length={l}>\n")
    f.write("#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tGSYNTH\n")
    f.write("chr19\t44900000\t.\tA\t<NON_REF>\t.\t.\tEND=44908683\tGT:DP:GQ:MIN_DP\t0/0:30:60:25\n")
    f.write("chr19\t44908684\t.\tT\tC,<NON_REF>\t60\t.\t.\tGT:DP:GQ\t0/1:31:60\n")
    f.write("chr19\t44908685\t.\tG\t<NON_REF>\t.\t.\tEND=44910000\tGT:DP:GQ:MIN_DP\t0/0:28:60:20\n")
    f.write("chr1\t11794419\t.\tT\tG,<NON_REF>\t55\t.\t.\tGT:DP:GQ\t1/1:22:50\n")

# Synthetic liftover chains covering the fixture regions (offsets match the real assemblies).
with open("hg19ToHg38.chain", "w") as f:
    f.write("chain 100000 chr19 59128983 + 45400000 45420000 chr19 58617616 + 44896743 44916743 1\n20000\n\n")
    f.write("chain 90000 chr1 249250621 + 11850000 11860000 chr1 248956422 + 11789943 11799943 2\n10000\n\n")
    f.write("chain 80000 chr2 243199373 + 136600000 136610000 chr2 242193529 + 135842430 135852430 3\n10000\n\n")
with open("hg38ToHg19.chain", "w") as f:
    f.write("chain 100000 chr19 58617616 + 44896743 44916743 chr19 59128983 + 45400000 45420000 1\n20000\n\n")
    f.write("chain 90000 chr1 248956422 + 11789943 11799943 chr1 249250621 + 11850000 11860000 2\n10000\n\n")
    f.write("chain 80000 chr2 242193529 + 135842430 135852430 chr2 243199373 + 136600000 136610000 3\n10000\n\n")
print("ok")
